In [1]:
import torch

In [3]:
torch.ones((2,), dtype=torch.int8)

tensor([1, 1], dtype=torch.int8)

In [4]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.ones((2,3),dtype=torch.int8)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)

In [6]:
torch.zeros((2,3), dtype=torch.int8)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int8)

In [7]:
torch.zeros((2,3)).dtype

torch.float32

In [8]:
torch.empty((2,3))

tensor([[0.0000e+00, 0.0000e+00, 7.2646e+22],
        [7.2250e+28, 2.5226e-18, 2.4283e-18]])

In [9]:
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

In [10]:
torch.full((2, 3), 3)

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [11]:
torch.rand((2,3))

tensor([[0.3088, 0.3042, 0.5855],
        [0.0776, 0.7097, 0.6423]])

In [12]:
torch.randint(10, 100, (2,3))

tensor([[77, 11, 37],
        [82, 78, 83]])

In [13]:
torch.randn((2,3))

tensor([[-1.8856, -0.4864, -0.6250],
        [-0.2469,  0.1903, -1.4959]])

In [14]:
torch.tensor([[1, 2 ,3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
torch.as_tensor([[1., 2 ,3], [4, 5, 6]])

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [16]:
a = torch.tensor([[1, 2 ,3], [4, 5, 6]])

In [17]:
a.dtype

torch.int64

In [18]:
a.shape

torch.Size([2, 3])

In [19]:
b = torch.ones_like(a)

In [20]:
b

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
a.new_tensor([[0., 1.]])

tensor([[0, 1]])

In [22]:
a.new_full((2,2), 3.)

tensor([[3, 3],
        [3, 3]])

In [24]:
a.size()

torch.Size([2, 3])

In [26]:
a.dtype

torch.int64

In [27]:
b.numel()

6

In [3]:
import numpy as np
a = np.random.rand(2,3)
a

array([[0.50782883, 0.73330275, 0.85890837],
       [0.71611791, 0.34825074, 0.57269274]])

In [4]:
a = np.ones((2, 3))

In [5]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
b = torch.from_numpy(a)

In [8]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [73]:
b.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]])

In [74]:
a *= 2

In [75]:
a

array([[2., 2., 2.],
       [2., 2., 2.]])

In [76]:
b

tensor([[2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)

In [10]:
b = torch.ones((2,3))

In [11]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
b.requires_grad

False

In [13]:
a = torch.ones((2,3),requires_grad=True)

In [14]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [15]:
a.requires_grad

True

In [68]:
a = torch.full((2,3), 4, requires_grad=True)

In [69]:
a

tensor([[4., 4., 4.],
        [4., 4., 4.]], requires_grad=True)

In [84]:
b = (a**2+3).sum()

tensor(210., grad_fn=<SumBackward0>)

In [88]:
b.grad_fn

In [72]:
b.requires_grad

True

In [73]:
b.backward()

In [74]:
a.grad

tensor([[16., 16., 16.],
        [16., 16., 16.]])

In [132]:
x = torch.full((2,3), 4,requires_grad=True)

In [80]:
y = 2*x+3

In [81]:
y

tensor([[11., 11., 11.],
        [11., 11., 11.]], grad_fn=<AddBackward0>)

In [123]:
x

tensor([[4., 4., 4.],
        [4., 4., 4.]], requires_grad=True)

In [124]:
y = (2*x**2+3)

In [125]:
y

tensor([[35., 35., 35.],
        [35., 35., 35.]], grad_fn=<AddBackward0>)

In [126]:
y.backward(torch.ones_like(x))

In [127]:
x.grad

tensor([[16., 16., 16.],
        [16., 16., 16.]])

In [128]:
y.grad

In [129]:
x.requires_grad

True

In [130]:
x.requires_grad_(False)

tensor([[4., 4., 4.],
        [4., 4., 4.]])

In [131]:
x.requires_grad

False

In [139]:
x.requires_grad

True

In [141]:
with torch.no_grad():
    print(x.requires_grad)

True


In [138]:
y.requires_grad

True

In [148]:
x = torch.randn(3, requires_grad=True)
print(x.requires_grad)
print((x ** 2).requires_grad)
y = x**2
print(y.requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)
    print(y.requires_grad)

True
True
True
False
True


In [154]:
a = torch.Tensor([1, 2, 3, 4])
torch.reshape(a, (2, 2))

tensor([[1., 2.],
        [3., 4.]])

In [167]:
a = torch.Tensor([1, 2, 3, 4, 5, 6])
a.resize_((2, 2))

tensor([[1., 2.],
        [3., 4.]])

In [161]:
torch.arange(1.,7.).resize_(2,3)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [163]:
torch.arange(1.,7.)

tensor([1., 2., 3., 4., 5., 6.])

In [172]:
a = torch.Tensor([1, 2, 3, 4, 5, 6])
a.view((2, -1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [173]:
a = torch.Tensor([1, 2, 3, 4, 5, 6])
a.view((2, 3))

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [179]:
a = torch.Tensor([[1, 2, 3], 
                 [4, 5, 6]])
b = torch.Tensor([4,5,6,7,8,9])

In [180]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [181]:
b

tensor([4., 5., 6., 7., 8., 9.])

In [182]:
b.view_as(a)

tensor([[4., 5., 6.],
        [7., 8., 9.]])

In [183]:
b

tensor([4., 5., 6., 7., 8., 9.])