In [1]:
import torch
import torch.nn as nn

In [2]:
nn.Conv2d(3, 16, 3, padding=1)

Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

In [3]:
nn.Conv2d(3, 16, 3, stride=2, padding=(1,2))

Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 2))

In [4]:
nn.Conv2d(3, 16, (3,4), padding=1)

Conv2d(3, 16, kernel_size=(3, 4), stride=(1, 1), padding=(1, 1))

In [5]:
nn.Conv2d(3, 16, (3,4), padding=(1,4))

Conv2d(3, 16, kernel_size=(3, 4), stride=(1, 1), padding=(1, 4))

In [6]:
nn.Conv2d(3, 16, (3,4), stride=(3,3), padding=(1,2))

Conv2d(3, 16, kernel_size=(3, 4), stride=(3, 3), padding=(1, 2))

In [7]:
nn.Conv2d(3, 16, (3,4), stride=3, padding=(1,2))

Conv2d(3, 16, kernel_size=(3, 4), stride=(3, 3), padding=(1, 2))

In [8]:
nn.Conv2d(3, 16, 3)

Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1))

In [9]:
nn.Conv2d(3, 16, 3, stride=2)

Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2))

In [10]:
max_pool = nn.MaxPool2d(3, stride=1)

In [11]:
a = torch.FloatTensor(3,5,5).random_(0, 10)

In [12]:
a

tensor([[[8., 0., 2., 9., 8.],
         [0., 5., 4., 9., 0.],
         [1., 3., 7., 4., 9.],
         [5., 9., 4., 4., 6.],
         [7., 8., 9., 2., 9.]],

        [[6., 6., 1., 5., 9.],
         [3., 8., 3., 6., 1.],
         [9., 5., 4., 4., 2.],
         [5., 6., 5., 6., 5.],
         [7., 6., 2., 5., 6.]],

        [[6., 6., 7., 4., 9.],
         [4., 3., 2., 4., 4.],
         [3., 0., 5., 7., 6.],
         [6., 3., 1., 0., 4.],
         [3., 3., 5., 0., 7.]]])

In [13]:
max_pool(a)

tensor([[[8., 9., 9.],
         [9., 9., 9.],
         [9., 9., 9.]],

        [[9., 8., 9.],
         [9., 8., 6.],
         [9., 6., 6.]],

        [[7., 7., 9.],
         [6., 7., 7.],
         [6., 7., 7.]]])

In [14]:
avg_pool = nn.AvgPool2d(3, stride=1)

In [15]:
avg_pool(a)

tensor([[[3.3333, 4.7778, 5.7778],
         [4.2222, 5.4444, 5.2222],
         [5.8889, 5.5556, 6.0000]],

        [[5.0000, 4.6667, 3.8889],
         [5.3333, 5.2222, 4.0000],
         [5.4444, 4.7778, 4.3333]],

        [[4.0000, 4.2222, 5.3333],
         [3.0000, 2.7778, 3.6667],
         [3.2222, 2.6667, 3.8889]]])

In [16]:
from torchvision import datasets

In [17]:
from torchvision import transforms

In [18]:
transforms.ToTensor()

ToTensor()

In [19]:
transforms.Resize(1)

Resize(size=1, interpolation=PIL.Image.BILINEAR)

In [20]:
transforms.Resize((1,1))

Resize(size=(1, 1), interpolation=PIL.Image.BILINEAR)

In [21]:
transforms.Pad(1, 0)

Pad(padding=1, fill=0, padding_mode=constant)

In [22]:
transforms.Pad((1, 2), 1)

Pad(padding=(1, 2), fill=1, padding_mode=constant)

In [23]:
transforms.Pad((1, 2, 2, 3), padding_mode='reflect')

Pad(padding=(1, 2, 2, 3), fill=0, padding_mode=reflect)

In [24]:
transforms.Normalize((0.5,),(0.5,))

Normalize(mean=(0.5,), std=(0.5,))

In [25]:
transforms.Compose([
     transforms.CenterCrop(10),
     transforms.ToTensor(),
])

Compose(
    CenterCrop(size=(10, 10))
    ToTensor()
)

In [26]:
transforms.CenterCrop(10)

CenterCrop(size=(10, 10))

In [27]:
transforms.RandomCrop(10)

RandomCrop(size=(10, 10), padding=None)

In [28]:
transforms.RandomCrop((10, 20))

RandomCrop(size=(10, 20), padding=None)

In [29]:
transforms.RandomHorizontalFlip(p=0.3)

RandomHorizontalFlip(p=0.3)

In [30]:
transforms.RandomVerticalFlip(p=0.3)

RandomVerticalFlip(p=0.3)

In [31]:
transforms.ColorJitter(0.25, 0.25, 0.25, 0.25)

ColorJitter(brightness=[0.75, 1.25], contrast=[0.75, 1.25], saturation=[0.75, 1.25], hue=[-0.25, 0.25])

In [32]:
transforms.RandomRotation(10)

RandomRotation(degrees=(-10, 10), resample=False, expand=False)

In [33]:
transforms.Compose([
     transforms.RandomRotation(10),
     transforms.ToTensor(),
])

Compose(
    RandomRotation(degrees=(-10, 10), resample=False, expand=False)
    ToTensor()
)

In [34]:
transformations = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(20),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5),(0.5, 0.5, 0.5))
])

In [35]:
train_data = datasets.CIFAR10('CIFAR10', train=True, download=True, transform=transformations)

Files already downloaded and verified


In [36]:
test_data = datasets.CIFAR10('CIFAR10', train=False, download=True, transform=transformations)

Files already downloaded and verified


In [37]:
len(train_data), len(test_data)

(50000, 10000)

In [38]:
from torch.utils.data.sampler import SubsetRandomSampler

In [39]:
validation_size = 0.2

In [40]:
import numpy as np

In [41]:
training_size = len(train_data)

In [42]:
indices = list(range(training_size))

In [43]:
np.random.shuffle(indices)

In [44]:
index_split = int(np.floor(training_size * validation_size))

In [45]:
validation_indices, training_indices = indices[:index_split], indices[index_split:]

In [46]:
training_sample = SubsetRandomSampler(training_indices)
validation_sample = SubsetRandomSampler(validation_indices)

In [47]:
batch_size = 16

In [48]:
from torch.utils.data.dataloader import DataLoader

In [49]:
train_loader = DataLoader(train_data, batch_size=batch_size, sampler=training_sample)
valid_loader = DataLoader(train_data, batch_size=batch_size, sampler=validation_sample)
test_loader = DataLoader(train_data, batch_size=batch_size)

In [50]:
import torch.nn as nn
import torch.nn.functional as F

In [51]:
class CNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 16, 3, padding=1)
        self.conv2 = nn.Conv2d(16, 32, 3, padding=1)
        self.conv3 = nn.Conv2d(32, 64, 3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.linear1 = nn.Linear(64 * 4 * 4, 512)
        self.linear2 = nn.Linear(512, 10) 
        self.dropout = nn.Dropout(p=0.3)
    
    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))
        x = x.view(-1, 64 * 4 * 4)
        x = self.dropout(x)
        x = F.relu(self.linear1(x))
        x = self.dropout(x)
        x = self.linear2(x)
        return x

In [52]:
model = CNN()

In [53]:
model

CNN(
  (conv1): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv2): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv3): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (linear1): Linear(in_features=1024, out_features=512, bias=True)
  (linear2): Linear(in_features=512, out_features=10, bias=True)
  (dropout): Dropout(p=0.3, inplace=False)
)

In [54]:
from torchsummary import summary

In [55]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [56]:
device.type

'cuda'

In [57]:
model = model.to(device)

In [58]:
criterion = nn.CrossEntropyLoss()

In [59]:
import torch.optim as optim

In [60]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [61]:
n_epochs = 30

In [62]:
def accuracy(preds, y):
    _, pred = torch.argmax(preds, 1)
    correct = pred.eq(target.data.view_as(pred))
    acc = correct.sum()/len(correct)
    return acc

In [63]:
for epoch in range(1, n_epochs+1):
    train_loss = 0.0
    valid_loss = 0.0
    
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()*data.size(0)
        
    model.eval()
    for batch_idx, (data, target) in enumerate(valid_loader):
        data, target = data.to(device), target.to(device)
        output = model(data)
        loss = criterion(output, target)
        valid_loss += loss.item()*data.size(0)
        
    train_loss = train_loss/len(train_loader.sampler)
    valid_loss = valid_loss/len(valid_loader.sampler)
    
    print(f'| Epoch: {epoch:02} | Train Loss: {train_loss:.3f} | Val. Loss: {valid_loss:.3f} |')

| Epoch: 01 | Train Loss: 2.057 | Val. Loss: 1.768 |
| Epoch: 02 | Train Loss: 1.660 | Val. Loss: 1.516 |
| Epoch: 03 | Train Loss: 1.507 | Val. Loss: 1.424 |


In [64]:
torch.save(model.state_dict(), "cifar10.pth")